### ISSUE TITLE
PropTypes is deprecated.

### ISSUE THREAD

**Issue by jorgegonzalez** [react-grid-layout/react-draggable#238]
I'm getting the following warning, and I'm not sure if this issue has already been raised: 

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by STRML** [comment]
Yep, will migrate this shortly. PRs welcome.

**Comment by jorgegonzalez** [comment]
I'll try and open a PR tonight.

**Comment by STRML** [comment]
Fixed in 2.2.4

**Comment by human-a** [comment]
Hi, I have upgraded to the latest version your plugin but I still get the PropType deprecated error in my console.

I am using:

"react": "^15.5.4",
"react-dom": "^15.5.4",
"react-draggable": "^2.2.6",
"react-redux": "^5.0.5",
